#!/usr/bin/env bash
set -euo pipefail

# Generate a gdb init snippet that maps ROS 2 Debian build paths to local sources.
# This avoids hardcoding /usr/src/... versions inside launch.json.
#
# Output:
#   <repo_root>/.vscode/ros2_sources.gdbinit
#
# Usage:
#   ./ros2_ws/scripts/gen_gdb_source_map.sh [ros_distro]

ros_distro="${1:-jazzy}"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
out_dir="${repo_root}/.vscode"
out_file="${out_dir}/ros2_sources.gdbinit"

mkdir -p "${out_dir}"

# Compute exact Debian versions (these often appear in DWARF comp_dir as /usr/src/ros-<distro>-<pkg>-<Version>)
rclcpp_ver=""
rcutils_ver=""
if command -v dpkg-query >/dev/null 2>&1; then
  rclcpp_ver="$(dpkg-query -W -f='${Version}' "ros-${ros_distro}-rclcpp" 2>/dev/null || true)"
  rcutils_ver="$(dpkg-query -W -f='${Version}' "ros-${ros_distro}-rcutils" 2>/dev/null || true)"
fi

# Fallback: try to discover a matching /usr/src directory if dpkg-query isn't available.
if [[ -z "${rclcpp_ver}" ]]; then
  guess="$(ls -d "/usr/src/ros-${ros_distro}-rclcpp-"* 2>/dev/null | head -n 1 || true)"
  if [[ -n "${guess}" ]]; then
    rclcpp_src_build="${guess}"
  else
    rclcpp_src_build=""
  fi
else
  rclcpp_src_build="/usr/src/ros-${ros_distro}-rclcpp-${rclcpp_ver}"
fi

if [[ -z "${rcutils_ver}" ]]; then
  guess="$(ls -d "/usr/src/ros-${ros_distro}-rcutils-"* 2>/dev/null | head -n 1 || true)"
  if [[ -n "${guess}" ]]; then
    rcutils_src_build="${guess}"
  else
    rcutils_src_build=""
  fi
else
  rcutils_src_build="/usr/src/ros-${ros_distro}-rcutils-${rcutils_ver}"
fi

{
  echo "# Auto-generated by ros2_ws/scripts/gen_gdb_source_map.sh"
  echo "# Repo root: ${repo_root}"
  echo "set debuginfod enabled on"
  echo "set debuginfod urls https://debuginfod.ubuntu.com"
  echo "cd ${repo_root}"
  echo "directory ${repo_root}/third_party/glibc"

  # glibc build-relative mappings (useful when stepping into libc startup)
  echo "set substitute-path ./csu ${repo_root}/third_party/glibc/csu"
  echo "set substitute-path ./sysdeps ${repo_root}/third_party/glibc/sysdeps"
  echo "set substitute-path ./string/../sysdeps ${repo_root}/third_party/glibc/sysdeps"

  # libstdc++ common Ubuntu build path mappings (best-effort)
  echo "set substitute-path /build/gcc-14-ig5ci0/gcc-14-14.2.0/build/x86_64-linux-gnu/libstdc++-v3/include /usr/include/c++/13"
  echo "set substitute-path /build/gcc-14-ig5ci0/gcc-14-14.2.0/build/x86_64-linux-gnu/libstdc++-v3/include/x86_64-linux-gnu /usr/include/x86_64-linux-gnu/c++/13"

  if [[ -n "${rclcpp_src_build}" ]]; then
    echo "set substitute-path ${rclcpp_src_build} ${repo_root}/third_party/rclcpp_repo"
  else
    echo "# NOTE: rclcpp build path not detected; run dpkg-query or install ros-${ros_distro}-rclcpp"
  fi

  if [[ -n "${rcutils_src_build}" ]]; then
    echo "set substitute-path ${rcutils_src_build} ${repo_root}/third_party/rcutils_repo"
  else
    echo "# NOTE: rcutils build path not detected; run dpkg-query or install ros-${ros_distro}-rcutils"
  fi
} >"${out_file}"

echo "[gen_gdb_source_map] Wrote: ${out_file}"
if [[ -n "${rclcpp_src_build}" ]]; then
  echo "[gen_gdb_source_map] rclcpp: ${rclcpp_src_build} -> ${repo_root}/third_party/rclcpp_repo"
fi
if [[ -n "${rcutils_src_build}" ]]; then
  echo "[gen_gdb_source_map] rcutils: ${rcutils_src_build} -> ${repo_root}/third_party/rcutils_repo"
fi
